[package]
name = "enum_from_strings"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.28"
sqlx = { version = "0.6.3", features = ["mysql", "runtime-tokio-rustls"] }
syn = "2.0.18"
tokio = { version = "1.28.2", features = ["full"] }
